package cmd

import (
	"fmt"
	"path/filepath"

	"github.com/cszatma/go-fish/fatal"
	"github.com/cszatma/go-fish/git"
	"github.com/cszatma/go-fish/hooks"
	"github.com/cszatma/go-fish/util"
	p "github.com/cszatma/printer"
	"github.com/spf13/cobra"
)

var (
	shouldRemoveAll bool
)

var uninstallCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Uninstall the git hooks",
	Long: `Uninstall will remove all the git hooks generated by go-fish.
By default it will not touch hooks not created by go-fish.`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println(p.Cyan("Uninstalling git hooks..."))
		util.VerbosePrintln("Finding .git directory")
		_, gitDir, err := git.RootDir()
		if err != nil {
			fatal.ExitErr(err, "Failed to find .git directory")
		}

		util.VerbosePrintln("Removing git hooks...")
		hooksPath := filepath.Join(gitDir, "hooks")
		err = hooks.RemoveHooks(hooksPath, shouldRemoveAll)
		if err != nil {
			fatal.ExitErr(err, "Failed to remove git hooks")
		}

		fmt.Println(p.Green("Successfully uninstalled Git hooks! 🎣"))
	},
}

func init() {
	uninstallCmd.Flags().BoolVarP(&shouldRemoveAll, "all", "a", false, "deletes all hooks including ones not generated by go-fish")
	rootCmd.AddCommand(uninstallCmd)
}
